<HTML>
<HEAD>
<meta charset="UTF-8">
<title>CouldNotStartFlowException - corda</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">corda</a>&nbsp;/&nbsp;<a href="../index.html">net.corda.client.rpc.reconnect</a>&nbsp;/&nbsp;<a href="./index.html">CouldNotStartFlowException</a><br/>
<br/>
<h1>CouldNotStartFlowException</h1>
<code><span class="keyword">class </span><span class="identifier">CouldNotStartFlowException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="../../net.corda.client.rpc/-r-p-c-exception/index.html"><span class="identifier">RPCException</span></a></code>
<p>Thrown when a flow start command died before receiving a <a href="../../net.corda.core.messaging/-flow-handle/index.html">net.corda.core.messaging.FlowHandle</a>.
On catching this exception, the typical behaviour is to run a "logical retry", meaning only retry the flow if the expected outcome did not occur.</p>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="-init-.html">&lt;init&gt;</a></h4>
</td>
<td>
<p>Thrown when a flow start command died before receiving a <a href="../../net.corda.core.messaging/-flow-handle/index.html">net.corda.core.messaging.FlowHandle</a>.
On catching this exception, the typical behaviour is to run a "logical retry", meaning only retry the flow if the expected outcome did not occur.</p>
<code><span class="identifier">CouldNotStartFlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.client.rpc.reconnect.CouldNotStartFlowException$<init>(kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span>&nbsp;<span class="symbol">=</span>&nbsp;null<span class="symbol">)</span></code></td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
